version: "2.0"
services:
    influxdb:
      image: hypriot/rpi-influxdb
      ports:
       - "8086:8086"
       - "8083:8083"
      environment:
       - INFLUXDB_USER=root
       - INFLUXDB_PASS=root
       - INFLUXDB_NAME=stats
    grafana:
      build: docker/grafana
      environment:
       - NO_PROXY="influxdb"
      links:
       - influxdb
      ports:
       - "3000:3000"

