version: "2.0"
services:
    influxdb:
      image: influxdb
      ports:
       - "8086:8086"
       - "8083:8083"
      environment:
       - INFLUXDB_USER=root
       - INFLUXDB_PASS=root
       - INFLUXDB_NAME=stats
    grafana:
      build: docker/grafana
      environment:
       - NO_PROXY="influxdb"
       - GF_SERVER_ROOT_URL=BASE_URL_AND_SUBPATH/ # e.g. https://www.my-page.de, https://dashboard.my-page.de, https://my-page.de/dashboard
      links:
       - influxdb
      ports:
       - "3000:3000"

