apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    service: grafana
spec:
  selector:
    service: grafana
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
