apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: neinkeinkaffee/grafana
        env:
          - name: NO_PROXY
            value: influxdb
          - name: GF_SERVER_ROOT_URL
            value: BASE_URL_AND_PATH
      restartPolicy: Always
