apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  labels:
    name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          env:
            - name: INFLUXDB_USER
              value: root
            - name: INFLUXDB_PASSWORD
              value: root
            - name: INFLUXDB_NAME
              value: stats
          volumeMounts:
            - name: influxdb-volume-mount
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-volume-mount
          persistentVolumeClaim:
            claimName: influxdb-pvc
      restartPolicy: Always
