apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    service: influxdb
spec:
  selector:
    service: influxdb
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
    - port: 8086
      protocol: TCP
      targetProt: 8086