apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
        - name: prometheus
          image: neinkeinkaffee/prometheus
          volumeMounts:
            - name: prometheus-volume-mount
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-volume-mount
          persistentVolumeClaim:
            claimName: prometheus-pvc
      restartPolicy: Always
