apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    service: prometheus
spec:
  selector:
    service: prometheus
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
